### model
model_name_or_path: meta-llama/Llama-3.1-70B-Instruct
quantization_bit: 4
quantization_method: bitsandbytes
double_quantization: false
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_target: all
#deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: deepseek_medicine_noCOT_train
template: llama3
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-70b/noCOT/qlora/4bit/epoch20_rank64_lr10e-5
logging_steps: 60
save_steps: 60
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: deepseek_medicine_noCOT_val
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 60
